# -*- coding: utf-8 -*-
"""Mad_Libs_Game_Pro1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ans0CNF4wa1ze0SoOGxqUmL4sCeoxt1s

# **Mad Libs Game In Python**
"""

# Take User Input
name = input("Enter the Girl's Name: ")
course_Name = input("Enter the Course Name (e.g., Artificial Intelligence, Blockchain, Web Development): ")
programming_lang = input("Enter the Programming Language (e.g., HTML, TypeScript, Next.js, Python): ")
mentor = input("Enter the Mentor's Name: ")
haunted_place = input("Enter the Haunted Place: ")

# Story created
print("\nHere is my short story based on the Mad Libs Game!")
print(f"Once upon a time, there was a girl named {name}, a dedicated student of PIAIC and GIAIC. She was enrolled in the {course_Name} course and had a deep passion for {programming_lang}. Under the guidance of her mentor, {mentor}, she worked tirelessly to master her skills.")

print(f"One night, {name} had to visit {haunted_place} to complete a research project. She also had a late-night shift at the same place. When her class was over, she decided to stay a little longer, reviewing her notes and perfecting her code. The once-crowded Bahria Auditorium was now eerily empty. As she typed, the stage lights flickered, and from the corner of her eye, she saw a shadowy figure standing motionless on the stage.")

print(f"A chill ran down her spine, but she brushed it off as exhaustion. Moments later, the auditorium's main door creaked open on its own. A sudden gust of wind sent her papers flying. She hurried to pick them up, only to find a single, unfamiliar sheet among them. It was filled with cryptic symbols and an unsettling message: 'YOU DO NOT BELONG HERE.'")

print(f"Her laptop screen began to glitch violently. Lines of unfamiliar code scrolled endlessly, flashing warnings in deep red. Then, the power went out. Only the glow of her laptop remained, illuminating a ghostly figure reflected on the screen—its hollow eyes staring directly into hers. A guttural whisper echoed through the room: 'Leave... before it's too late.'")

print(f"Frozen in terror, {name} tried to shut down her laptop, but an unseen force kept her hands locked to the keyboard. The auditorium doors slammed shut. A sinister laughter filled the room as the black figure on stage started moving toward her. Her heart pounded as the screen displayed a final, chilling message: 'RUN.'")

print(f"She let out a bloodcurdling scream as the darkness consumed her. The next morning, the janitor found her belongings neatly placed on the front row seat—but {name} was nowhere to be found. Her laptop remained open, displaying one haunting error message: '404: SOUL NOT FOUND.'")

print("And from that day on, every student who opens that laptop hears a whisper—a whisper that knows their name...")